const movies = [
  {
    id: 1,
    name: "Свадьба в Малиновке",
    link: "http://www.ljplus.ru/img2/r/u/ru_kino_posters/1967_svadba_v_malinovke.jpg",
    duration: "1ч 30мин",
    trailerLink: "https://www.kinopoisk.ru/film/44045/",
  },
  {
    id: 2,
    name: "Иван Васильевич меняет профессию",
    link: "https://sun9-20.userapi.com/tET_ifXq2b9LivABfhvg81SU_oFfE_FmCOTvvA/27Hhzq2mz5c.jpg",
    duration: "1ч 22мин",
    trailerLink: "https://www.kinopoisk.ru/film/42664/",
  },
  {
    id: 3,
    name: "Кавказская пленница",
    link: "https://static.tildacdn.com/tild3830-6531-4262-a138-346530336635/scale_1200.jpg",
    duration: "1ч 22мин",
    trailerLink: "https://www.kinopoisk.ru/film/44745/",
  },
  {
    id: 4,
    name: "Служебный роман",
    link: "https://main-cdn.sbermegamarket.ru/hlr-system/127/451/373/831/195/0/600004450671b0.jpeg",
    duration: "2ч 39мин",
    trailerLink: "https://www.kinopoisk.ru/film/43869/",
  },
  {
    id: 5,
    name: "Любовь и голуби",
    link: "http://images-s.kinorium.com/movie/poster/80608/w1500_50229067.jpg",
    duration: "1ч 47мин",
    trailerLink: "https://www.kinopoisk.ru/film/45146/",
  },
  {
    id: 6,
    name: "Мимино",
    link: "https://www.mentoday.ru/upload/img_cache/b22/b228078b1456c81e90791e4cfb3db53e_cropped_1332x1076.jpg",
    duration: "1ч 32мин",
    trailerLink: "https://www.kinopoisk.ru/film/46638/",
  },
  {
    id: 7,
    name: "Афоня",
    link: "https://i.ytimg.com/vi/yqrDzigxhew/maxresdefault.jpg",
    duration: "1ч 32мин",
    trailerLink: "https://www.kinopoisk.ru/film/43423/",
  },
  {
    id: 8,
    name: "Афоня",
    link: "https://i.ytimg.com/vi/yqrDzigxhew/maxresdefault.jpg",
    duration: "1ч 32мин",
    trailerLink: "https://www.kinopoisk.ru/film/43423/",
  },
  {
    id: 9,
    name: "Афоня",
    link: "https://i.ytimg.com/vi/yqrDzigxhew/maxresdefault.jpg",
    duration: "1ч 32мин",
    trailerLink: "https://www.kinopoisk.ru/film/43423/",
  },
  {
    id: 10,
    name: "Афоня",
    link: "https://i.ytimg.com/vi/yqrDzigxhew/maxresdefault.jpg",
    duration: "1ч 32мин",
    trailerLink: "https://www.kinopoisk.ru/film/43423/",
  },
  {
    id: 11,
    name: "Афоня",
    link: "https://i.ytimg.com/vi/yqrDzigxhew/maxresdefault.jpg",
    duration: "1ч 32мин",
    trailerLink: "https://www.kinopoisk.ru/film/43423/",
  },
  {
    id: 12,
    name: "Афоня",
    link: "https://i.ytimg.com/vi/yqrDzigxhew/maxresdefault.jpg",
    duration: "1ч 32мин",
    trailerLink: "https://www.kinopoisk.ru/film/43423/",
  },
  {
    id: 13,
    name: "Афоня",
    link: "https://i.ytimg.com/vi/yqrDzigxhew/maxresdefault.jpg",
    duration: "1ч 32мин",
    trailerLink: "https://www.kinopoisk.ru/film/43423/",
  },
  {
    id: 14,
    name: "Афоня",
    link: "https://i.ytimg.com/vi/yqrDzigxhew/maxresdefault.jpg",
    duration: "1ч 32мин",
    trailerLink: "https://www.kinopoisk.ru/film/43423/",
  },
  {
    id: 15,
    name: "Афоня",
    link: "https://i.ytimg.com/vi/yqrDzigxhew/maxresdefault.jpg",
    duration: "1ч 32мин",
    trailerLink: "https://www.kinopoisk.ru/film/43423/",
  },
];

export default movies;
